# Given: At most 10 DNA strings in FASTA format (of length at most 1 kbp each).
# Return: The ID of the string having the highest GC-content, followed by the GC-content of that string. Rosalind allows for a default error of 0.001 in all decimal answers unless otherwise stated; please see the note on absolute error below.

################# how to do it for one string ##################
# DNA strings
#Rosalind_0808 = "CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT"

# for every DNA string:
# count total length
#print(len(Rosalind_0808))

# if C or G count  -> GC_content
#amount_GC = []

#for i in Rosalind_0808:
#    if i == "G":
#        amount_GC += "G"
#    elif i == "C":
#        amount_GC += "C"
#    else:
#        continue   
#
#print(len(amount_GC))
# calculate percentage of GC in the DNA string    
#percent = len(amount_GC) * 100 / len(Rosalind_0808)
#print(percent)



# =================================================================== #



############# how to do it for more strings at the same time ########




# make a loop that goes over all strings
def string(DNA):
    amount_GC = []
    for i in DNA:
        if i == "G":
            amount_GC += "G"
        elif i == "C":
            amount_GC += "C"
        else:
            continue
    return amount_GC

# print amount of G and C for every string
# put string in ("")
GC_Rosalind_3699 = len(string("GGGGCCGTTTACTAGCAATATCTCTAAGGCAGTACACCAACACCTTTGCTTAGCTGTCTTGTGTCGGACGTGCGGTGACGCAGGGGGCGATCAGGATGTTACGAAGACGCAGAAAGTTCCTGGGTACTTTACAATTTGCAGGATCACAGCTTACTCGCGGTTCGGGTAGGGGGACAAGATTACTTCATAAATTAACCTCCAGGGGGCTAATGAGGGGTGATCTGATTTACGCCTAGACTGGCGATTTAGGGTAAGGTAATTGATCTTGGGTGATTCCATCATTGAACAAGACTACTATGGTCATTTGATCCGAGTAAGACCGATGGCATTGCAGGTATGATCCACGTCCGATACGGTCATGTCCTGTAGTGGCGTTGAGCCTGGGAGAAAAATTGTGACAATACCTCTGTCGCTGCCATCAAACACTGCGGGATTGGCAAAGGAGGCGACTACGATGACCCGACCAGCAGCACATTATATTAACTGCCTCAGCCATAGTTGGGCTCAGTAACCGTAACACTAAATACGTGTTCCAGCGGGCAGTTTTCCATTGATGCTCAATCTAGGCGAATTTGGATGAAGTCTGACGATTGTCCCTACCACAGTACACCCTAATTAACGAAACTTGCACATTCTCTAACGGGAAGCCAGACCTTAGACGCCTTTATCACGAATGGACTATTTATCACTCGGAGACTGCTGATGGAGAAAGCACCCGGTAAGTATTGAAGGTCAGAATGTGTCATTCGCAATTGCAAAAACCAACAGGCCCATCGTACGCCTCGTAGAGAAAGAGTCTTCGTGCATAAGTCTAGGCACCTG"))
GC_Rosalind_4007 = len(string("AGGCAAAGTTTAATGGACGGAACGACTCCGATCATCTTAAAGTCGCTATAATTCCAGCCACCCACGCCAACCCCCCACGCGACGATCTTAAATTATTCATTAGGGAGCACCTTGATGTACTATGGGACGGCAAAGCCTCATAAGCCCGGTTATGAGACCCATACCAGATCGCGCGCTCATGGACGGTTCCGTATCTTTCATAATATTCGTCTTATGGGAGCATGCTAGGTGGAGGGTTCAAGGCTCCGACCGTCAACGTGACTTACTGTTTCACAAGGATGGCAGCGTTCTCAGAAGGTGGGATACACACGCGATACGCACGATAAATGCTCTATCTGTAATTCTATAATCTCTCCAGACCACAGAAAATCAAAAACTGGCTACATTGAATCCTATTGAGATGCCCGACCATGCCAATGACCCCGAACCTGTGGAAGTTTGCATTGAACACTCCGCGTGACCAGCCTTCTTGCAAGAACCGTGCACAACAGATCCTCGATGTACAATCTGAGATACGGAGTCGTCATGTTACAGCCGACGTAATCCGTCCCAGCCTCCCTTGACTGCCCAATATACTCTCGGCATCGTTGAAAAGCTCCGGTAGGGGAGTAGTACAGTCCTGATCCTGTTCGACTATGGCATCTTCACTCAGAATCGGGGACCTTAGCGGGACGGTATTGAAACCCGAAATCGTGAACGCGAGGAGAAGAATCTACGCTATCTTGGCAGTAGAATTAAACACACAATCAGCTAGTTACGAGATTTAATGCGTGCTTCACTCCGCCGCACTCGACAATGGGACGTGTAAATTATTCCCGACGTCGTTGGCACCCGGAACTGCTATACCTTTTC"))
GC_Rosalind_0817 = len(string("ACACGAGTGACTTTGGTTATGGGTCGTGTGACGCTAGGTGCCTTGGTGGTACTTCCGAATTGTAGCGTTTTTCAAGGGAGCCCCTCAGCCGAACTTTCTGTTCTACTCGAACCATCACAATTACTCACGTAGGATACAGCGCGCGGCGATGCCCTTTGGCCAACGTTCCTCCTACTCAAAAGCGTGTCCTGTCGGCAGTAATTGTTACGTAGAGTCAACCTTTAGCTAGCCACATATTTAGTTTGGTGCATAAACATACATCAGGTGTCTTGAAGGTCGACGTTGATCCGATCGGGCTGGCGGCAGCCCGGAGTCCCTGACGCGGCGCAGCAGTTAGGCGGTCTGTAGGCCTCCTCCAAGGTTGACTATACAGACCTGGGCGTACACGACTGCCCTTTGCCAGCCGCCGCGACAAGTGTTTATCCGGGATGGCTCCTTATGACTTTGAGGAGTGCTCGCCCTAGAAAGCACCGATATCTACCGGACGCCGCGGTGGGCCCCACGCCCAGGTTTACCTTCGCAACAAGGCTACGGGCACAAGTTACTTGATACATCATGGTATGTTGCGGCTAGTTGGCCAGTAAAACGGACGATGTTCCACCACACGCGGGCTGTTACCCCGACCAGTACCACTTGTGAAATCAGCGCATTTCAGGGGTCTGATGGTACCGTGGATCTTATCCTGCACTAGGAGCTGTACCAACATAACTCCAAGACAAGGTTGCGGTAATGATGCTGCGATTAGAACCCATGCACTCTGTATCTAGGCTAAGCGTTATTGCACGTCGTAGGCTTTTAAATATCATAGAGGAGAGTTTTTTCGACTAGACTTTAATCTAGGGCTGGCTCCATCTC"))
# empty strings:
#Rosalind_xxxx = print(len(string("")))
#Rosalind_xxxx = print(len(string("")))
#Rosalind_xxxx = print(len(string("")))
                    
Rosalind_3699 = "GGGGCCGTTTACTAGCAATATCTCTAAGGCAGTACACCAACACCTTTGCTTAGCTGTCTTGTGTCGGACGTGCGGTGACGCAGGGGGCGATCAGGATGTTACGAAGACGCAGAAAGTTCCTGGGTACTTTACAATTTGCAGGATCACAGCTTACTCGCGGTTCGGGTAGGGGGACAAGATTACTTCATAAATTAACCTCCAGGGGGCTAATGAGGGGTGATCTGATTTACGCCTAGACTGGCGATTTAGGGTAAGGTAATTGATCTTGGGTGATTCCATCATTGAACAAGACTACTATGGTCATTTGATCCGAGTAAGACCGATGGCATTGCAGGTATGATCCACGTCCGATACGGTCATGTCCTGTAGTGGCGTTGAGCCTGGGAGAAAAATTGTGACAATACCTCTGTCGCTGCCATCAAACACTGCGGGATTGGCAAAGGAGGCGACTACGATGACCCGACCAGCAGCACATTATATTAACTGCCTCAGCCATAGTTGGGCTCAGTAACCGTAACACTAAATACGTGTTCCAGCGGGCAGTTTTCCATTGATGCTCAATCTAGGCGAATTTGGATGAAGTCTGACGATTGTCCCTACCACAGTACACCCTAATTAACGAAACTTGCACATTCTCTAACGGGAAGCCAGACCTTAGACGCCTTTATCACGAATGGACTATTTATCACTCGGAGACTGCTGATGGAGAAAGCACCCGGTAAGTATTGAAGGTCAGAATGTGTCATTCGCAATTGCAAAAACCAACAGGCCCATCGTACGCCTCGTAGAGAAAGAGTCTTCGTGCATAAGTCTAGGCACCTG"

Rosalind_4007 = "AGGCAAAGTTTAATGGACGGAACGACTCCGATCATCTTAAAGTCGCTATAATTCCAGCCACCCACGCCAACCCCCCACGCGACGATCTTAAATTATTCATTAGGGAGCACCTTGATGTACTATGGGACGGCAAAGCCTCATAAGCCCGGTTATGAGACCCATACCAGATCGCGCGCTCATGGACGGTTCCGTATCTTTCATAATATTCGTCTTATGGGAGCATGCTAGGTGGAGGGTTCAAGGCTCCGACCGTCAACGTGACTTACTGTTTCACAAGGATGGCAGCGTTCTCAGAAGGTGGGATACACACGCGATACGCACGATAAATGCTCTATCTGTAATTCTATAATCTCTCCAGACCACAGAAAATCAAAAACTGGCTACATTGAATCCTATTGAGATGCCCGACCATGCCAATGACCCCGAACCTGTGGAAGTTTGCATTGAACACTCCGCGTGACCAGCCTTCTTGCAAGAACCGTGCACAACAGATCCTCGATGTACAATCTGAGATACGGAGTCGTCATGTTACAGCCGACGTAATCCGTCCCAGCCTCCCTTGACTGCCCAATATACTCTCGGCATCGTTGAAAAGCTCCGGTAGGGGAGTAGTACAGTCCTGATCCTGTTCGACTATGGCATCTTCACTCAGAATCGGGGACCTTAGCGGGACGGTATTGAAACCCGAAATCGTGAACGCGAGGAGAAGAATCTACGCTATCTTGGCAGTAGAATTAAACACACAATCAGCTAGTTACGAGATTTAATGCGTGCTTCACTCCGCCGCACTCGACAATGGGACGTGTAAATTATTCCCGACGTCGTTGGCACCCGGAACTGCTATACCTTTTC"

Rosalind_0817 = "ACACGAGTGACTTTGGTTATGGGTCGTGTGACGCTAGGTGCCTTGGTGGTACTTCCGAATTGTAGCGTTTTTCAAGGGAGCCCCTCAGCCGAACTTTCTGTTCTACTCGAACCATCACAATTACTCACGTAGGATACAGCGCGCGGCGATGCCCTTTGGCCAACGTTCCTCCTACTCAAAAGCGTGTCCTGTCGGCAGTAATTGTTACGTAGAGTCAACCTTTAGCTAGCCACATATTTAGTTTGGTGCATAAACATACATCAGGTGTCTTGAAGGTCGACGTTGATCCGATCGGGCTGGCGGCAGCCCGGAGTCCCTGACGCGGCGCAGCAGTTAGGCGGTCTGTAGGCCTCCTCCAAGGTTGACTATACAGACCTGGGCGTACACGACTGCCCTTTGCCAGCCGCCGCGACAAGTGTTTATCCGGGATGGCTCCTTATGACTTTGAGGAGTGCTCGCCCTAGAAAGCACCGATATCTACCGGACGCCGCGGTGGGCCCCACGCCCAGGTTTACCTTCGCAACAAGGCTACGGGCACAAGTTACTTGATACATCATGGTATGTTGCGGCTAGTTGGCCAGTAAAACGGACGATGTTCCACCACACGCGGGCTGTTACCCCGACCAGTACCACTTGTGAAATCAGCGCATTTCAGGGGTCTGATGGTACCGTGGATCTTATCCTGCACTAGGAGCTGTACCAACATAACTCCAAGACAAGGTTGCGGTAATGATGCTGCGATTAGAACCCATGCACTCTGTATCTAGGCTAAGCGTTATTGCACGTCGTAGGCTTTTAAATATCATAGAGGAGAGTTTTTTCGACTAGACTTTAATCTAGGGCTGGCTCCATCTC"


percent = GC_Rosalind_3699 * 100 / len(Rosalind_3699)
print(percent)

percent = GC_Rosalind_4007 * 100 / len(Rosalind_4007)
print(percent)

percent = GC_Rosalind_0817 * 100 / len(Rosalind_0817)
print(percent)


# sort percentage of all DNA strings -> first one is highest


